lang: &lang
  name: "lang"
  label: "Lang"
  default: "en"
  widget: "select"
  options: &langOptions
    - { label: "English", value: "en" }
    - { label: "Chinese", value: "zh" }

backend:
  name: "github"
  repo: "connet-tw/connet"
  branch: "master"

publish_mode: "editorial_workflow"

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages-en"
    label: "Pages EN"
    files:
      - label: "About Page"
        name: "about"
        file: "src/data/content/about.en.yml"
        fields:
          - *lang
          - { label: "Title", name: "title" }
          - { label: "Subtitle", name: "subtitle", required: false }
          - { label: "Intro", name: "markdown", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
          - name: "referencesSection"
            label: "References"
            widget: "object"
            fields:
              - label: "Show references"
                name: "show"
                widget: "boolean"
                default: true
              - { label: "Title", name: "title" }
              - { label: "Subtitle", name: "subtitle", required: false }

  - name: "references en"
    label: "References EN"
    folder: "src/data/references"
    create: true
    fields:
      - *lang
      - { name: "date", label: "Date" }
      - { name: "title", label: "Title" }
      - { name: "customer", label: "Customer", required: false }
      - { name: "location", label: "Location", required: false }
      - { name: "body", label: "Content", widget: "markdown", required: false }

  - name: "services-en"
    label: "Services EN"
    folder: "src/data/services"
    filter: { field: "lang", value: "en" }
    create: true
    fields:
      - *lang
      - { name: "title", label: "Title" }
      - { name: "subtitle", label: "Subtitle" }
      - {
          name: "image",
          label: "Header Image",
          widget: "image",
          allow_multiple: false,
        }
      - { name: "order", label: "Order", widget: "number" }
      - { name: "body", label: "Content", widget: "markdown" }
